// Generate src/main/version.ts from git tag at build time
const { execSync } = require('child_process');
const { writeFileSync, mkdirSync } = require('fs');
const { join } = require('path');

let version = 'dev';
try {
  // Get the most recent tag reachable from HEAD, with commit count if ahead
  version = execSync('git describe --tags --always', { encoding: 'utf-8' }).trim();
} catch {
  try {
    version = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
  } catch { /* leave as 'dev' */ }
}

const outPath = join(__dirname, 'src', 'main', 'version.ts');
writeFileSync(outPath, `// Auto-generated by generate-version.js — do not edit\nexport const VERSION = '${version}';\n`);
console.log(`Version: ${version}`);
